addons:
  postgresql: '9.6'
before_script:
  - cp config/database.yml.travis config/database.yml
  - gem uninstall bundler -x
  - gem install bundler --version=1.13.7
dist: trusty
language: ruby
rvm:
  - 2.4.1
script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec
services:
  - postgresql
  - redis-server
